<?php
require_once('include/modules/validate.php');
class user extends appModel
{
	function __construct()
	{
		parent::__construct();
		if(VIEW=='edit')
			$this->validate=array(
			'name'=>'data',
			'required'=>array('username','mail'),
			'escape'=>'username',
			'mail'=>'mail'
			);
		elseif(VIEW=='password')
			$this->validate=array(
			'name'=>'data',
			'required'=>array('pass1','pass2','pass3'),
			'escape'=>array('pass1','pass2','pass3'),
			'crypt'=>array('pass1','pass2','pass3')
			);	
		elseif(VIEW=='login')	
			$this->validate=array(
			'name'=>'data',
			'required'=>array('username','password'),
			'escape'=>array('username','password'),
			'crypt'=>'password'
			);
		elseif(VIEW=='add')
			$this->validate=array(
			'name'=>'data',
			'required'=>array('username','password','repassword','mail'),
			'escape'=>array('username','password','repassword'),
			'mail'=>'mail',
			'crypt'=>array('password','repassword')
			);							
		parent::__construct();
	}
}
?>
